### ISSUE TITLE
Please fix tests to work without Internet

### ISSUE THREAD

**Issue by mgorny** [romis2012/python-socks#1]
It should be trivial to start a temporary local HTTP server from Python and use it instead of random sites.

**Comment by romis2012** [comment]
There are some reasons to use an external http resource. For example, we need to test DNS Resolvers (including the one on the proxy server side)

**Comment by mgorny** [comment]
It would be nice to have two sets of tests then. Right now we can't test this package (nor aiohttp-socks) at all in production.

**Comment by romis2012** [comment]
> It would be nice to have two sets of tests then

In any case, we'll not be able to test 3proxy dns resolver and therefore SOCKS5 remote dns

**Comment by romis2012** [comment]
Fixed
