### ISSUE TITLE
anyio.BrokenResourceError has no attribute 'errno'

### ISSUE THREAD

**Issue by yufengzjj** [romis2012/python-socks#16]
when anyio raise anyio.BrokenResourceError got AttributeError: 'BrokenResourceError' object has no attribute 'errno':

> File "/usr/local/lib/python3.9/dist-packages/python_socks/async_/anyio/_proxy.py", line 95, in connect
> Jan 22 17:19:40 scrap-spider python3[39395]:     raise ProxyConnectionError(e.errno, msg) from e
> Jan 22 17:19:40 scrap-spider python3[39395]: AttributeError: 'BrokenResourceError' object has no attribute 'errno'

**Comment by romis2012** [comment]
We shouldn't handle the OSError and BrokenResourceError exception together, that was my mistake...

**Comment by romis2012** [comment]
Fixed in version 2.0.3
