### ISSUE TITLE
Support for non-TLS proxy connections?

### ISSUE THREAD

**Issue by synchronizing** [romis2012/python-socks#18]
Is there anyway to connect to an HTTP proxy _without_ starting TLS/SSL / sending `CONNECT` statement? I find that even if I do:

```python
reader, writer = await asyncio.open_connection(
    host=None,
    port=None,
    sock=sock,
    ssl=None, # Explicitly written - but typically 'None' if not defined.
    server_hostname=None,
)
```

A `CONNECT` statement is _always_ sent to the proxy due to line 23 below.

https://github.com/romis2012/python-socks/blob/1e9c8c69953390a05c5ac830be709267f6cbe0e4/python_socks/_proto/http_async.py#L5-L33

Anyway to instead connect with the proxy, and then allow user to send whatever command they want from there on out?

**Comment by romis2012** [comment]
First of all, `python-socks` supports only `TUNNEL` (not `FORWARD`) HTTP proxies. So it always sends `CONNECT` command.

Secondly, using `CONNECT` method does not mean that you are establishing a secure (TLS) connection. `python-socks` itself does not call any "start tls" at all.

If you need a `FORWARD` http proxy (as I quess), use some http-client library ([httpcore](https://www.encode.io/httpcore/proxies/) for example)

**Comment by synchronizing** [comment]
Oh goodness, how embarrassing. You are completely right - lack of sleep made me forget `CONNECT` is part of the standard HTTP protocol for connecting to a proxy. Thank you for the reminder, closing this issue.
