### ISSUE TITLE
Support socks5h in python-socks

### ISSUE THREAD

**Issue by leonee** [romis2012/python-socks#21]
Do you have a plan to support socks5h directly in python-socks? If not, do you have any suggestion to use socks5h in asyncio library?

**Comment by romis2012** [comment]
`socks5h` (target host resolving on the proxy server side) is used by default. If you want to resolve target host locally, use 
 rdns argument of the Proxy ctor e.g. `Proxy.from_url(..., rdns=False)`

**Comment by leonee** [comment]
It works. Thx.
