### ISSUE TITLE
How to use with smtplib

### ISSUE THREAD

**Issue by huynhphuong10284** [romis2012/python-socks#26]
Hi all,

I want to use with smtplib, the following is my code. Please advise:

import smtplib
from python_socks.sync import Proxy

proxy = Proxy.from_url('socks5://username:password@p.webshare.io:80')
server = smtplib.SMTP()
server.sock = proxy
server.set_debuglevel(0)
try:
    server.connect('alt1.aspmx.l.google.com')
    print("connected")
    server.helo(server.local_hostname)
    code, message = server.rcpt(str(email))
    print(code, message)
    server.quit()

except:
    print("failed")

**Comment by romis2012** [comment]
You should override the `_get_socket` method of the `SMTP` class.  Something like this

```python
class ProxySMTP(smtplib.SMTP):
    def __init__(self, host, port, proxy_url):
        self._smtp_host = host
        self._smtp_port = port
        self._proxy_url = proxy_url
        super().__init__(host, port)

    def _get_socket(self, *args, **kwargs):
        proxy = Proxy.from_url(self._proxy_url)
        return proxy.connect(
            dest_host=self._smtp_host,
            dest_port=self._smtp_port,
        )
```
