### ISSUE TITLE
asyncio is part of Python stdlib

### ISSUE THREAD

**Issue by meehow** [romis2012/python-socks#3]
[The asyncio module is part of the Python standard library since Python 3.4.](https://pypi.org/project/asyncio/)

**Comment by romis2012** [comment]
> The asyncio module is part of the Python standard library since Python 3.4.

I know... What's the question?

**Comment by meehow** [comment]
There is no question. Just suggesting that you can remove asyncio from setup.py (and readme) because it requirest Python 3.6 anyway.

**Comment by romis2012** [comment]
Is `async-timeout` also part of the Python standard library?

**Comment by meehow** [comment]
Doesn't look so.

**Comment by romis2012** [comment]
So what's the issue?

**Comment by romis2012** [comment]
`asyncio` is extra requirement name,  not a dependency
