### ISSUE TITLE
How to set default proxy

### ISSUE THREAD

**Issue by Smawexi** [romis2012/python-socks#34]
How to set up a global proxy for modules developed based on the library itself, affecting asynchronous or non asynchronous modes.
Similar to Pysocks,  It can set a global proxy for standard library sockets in the following way, which can affect libraries like 'requets'
```
import socket
import socks

socks.set_default_proxy(socks.SOCKS5, "localhost")
socket.socket = socks.socksocket
```
I am not familiar with this library and do not know how to set a default proxy for third-party modules developed based on this library

**Comment by romis2012** [comment]
This "feature" is not supported
