### ISSUE TITLE
Feature Request: Support for HTTPS proxies

### ISSUE THREAD

**Issue by scottcrossen** [romis2012/python-socks#4]
Right now, _helpers.py:57 fails with:

```
ValueError: Invalid scheme component: https
```

https proxies are great for securely transferring auth headers to the proxy. I'm unsure as to whether this change would amount to whitelisting https and using the same http handler, or if a whole SSL routine will have to be written.

**Comment by romis2012** [comment]
>  I'm unsure as to whether this change would amount to whitelisting https and using the same http handler, or if a whole SSL routine will have to be written

The problem is more complex. In general case we need to implement "TLS in TLS" feature. Not all frameworks support it. See [this](https://github.com/aio-libs/aiohttp/issues/2722) discussion for details.

**Comment by scottcrossen** [comment]
Makes sense! Yep that's why I listed it as a feature request. If there are no plans to include it ever then feel free to close. I would love to have the expertise to add it myself but unfortunately I don't write python. :)
