### ISSUE TITLE
What is the difference with pysocks?

### ISSUE THREAD

**Issue by SantiagoTorres** [romis2012/python-socks#5]
Would it be useful to list the differences between this library and pysocks? Also, could this be a drop-in replacement.

**Comment by romis2012** [comment]
`python-socks` supports async API, `pysocks` does not.

**Comment by SantiagoTorres** [comment]
Aha! and is this a drop in? would a pysocks project just transparently be able to use it? I see that other than the module name differences (`socks` vs `python_socks`) the interface looks quite similar...

**Comment by romis2012** [comment]
In general no, they have a different interface

**Comment by SantiagoTorres** [comment]
ACK, I just wanted to make sure in order to keep things tidy for the archlinux repository. Thanks!
